name: iOS Standalone Publish

on: workflow_dispatch

jobs:
  ios_testflight_publish:
    name: iOS Testflight Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: bahmutov/npm-install@v1.1.0
      - uses: expo/expo-github-action@v5
        with:
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Run Expo Publish - iOS
        env:
          EXPO_APPLE_ID: ${{ secrets.APPLE_ID }}
          EXPO_APPLE_ID_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: expo upload:ios
